version: "3.9"

services:
  db:
    image: postgres:16
    container_name: dataexplorer_db
    environment:
      POSTGRES_DB: dataexplorer
      POSTGRES_USER: dataexplorer
      POSTGRES_PASSWORD: dataexplorer
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
